import vectorOverrides from './vectors.json' with { type: 'json' }

/**
 * vector の意味 (FANTYPE と互換、4軸):
 *  - shoubu : +が勝利至上(R)、-が美学(E)。
 *  - keiei  : +が補強派(W)、-が育成派(H)。経営規模/補強 vs 育成/忠誠/伝統。
 *  - kansen : +が熱狂派(U)、-が分析派(A)。コール文化 vs 戦術観戦。
 *  - kanshin: +が試合派(O)、-がカルチャー派(F)。90分集中 vs 365日関心。
 *
 * 下記の RAW_CLUBS が基準値。vectors.json および jlsp_vector_overrides テーブル
 * の値で上書きする。
 *
 * 注意: 60クラブ全件を保持しているが、JLSP では J1 (20クラブ) のみを CLUBS として export する。
 * 範囲を変える場合は CLUB_DIVISIONS の値を変更する。
 *
 * kanshin の初期値は全クラブ 0。後日 ryo さんが手動で各クラブの傾向 (例: 鹿島 = O 試合派、
 * 浦和 = F カルチャー派) を vectors.json or DB で上書きする想定。
 */
export const CLUB_DIVISIONS = ['J1']

export const RAW_CLUBS = [
  // ===== J1 =====
  { id: 'kashima',    name: '鹿島アントラーズ',          division: 'J1', region: '関東',   prefecture: '茨城県', color: '#E60012',
    vector: { shoubu: +2, keiei: +1, kansen:  0, kanshin:  0 },
    description: '「常勝」を背負う伝統クラブ。タイトル数はリーグ随一で、勝者のメンタリティが文化として根づいている。',
    stadiumGourmet: 'もつ煮、ハム焼き', sightseeing: '鹿島神宮、息栖神社', mascot: 'シカオ・ファミリー' },
  { id: 'urawa',      name: '浦和レッズ',                division: 'J1', region: '関東',   prefecture: '埼玉県', color: '#C8102E',
    vector: { shoubu: +2, keiei: +1, kansen: +2, kanshin:  0 },
    description: '日本一の動員と熱狂を誇る赤い軍団。タイトルへの渇望と圧倒的なホームの空気感が魅力。',
    stadiumGourmet: '浦和カレー、味噌だれ焼き鳥', sightseeing: 'うなぎの街・浦和、玉蔵院', mascot: 'レディア' },
  { id: 'kawasaki',   name: '川崎フロンターレ',          division: 'J1', region: '関東',   prefecture: '神奈川県', color: '#003490',
    vector: { shoubu: +1, keiei: -1, kansen: -1, kanshin:  0 },
    description: '緻密なパスワークと地域密着の両立を成し遂げた攻撃集団。リーグ屈指のポゼッションサッカー。',
    stadiumGourmet: '等々力グルメ、フロンターレ印のお米', sightseeing: '等々力緑地、川崎大師', mascot: 'ふろん太・カブレラ' },
  { id: 'f-marinos',  name: '横浜F・マリノス',            division: 'J1', region: '関東',   prefecture: '神奈川県', color: '#0033A0',
    vector: { shoubu: +2, keiei: +2, kansen: +1, kanshin:  0 },
    description: 'アタッキングフットボールを掲げ、超ハイラインの攻撃サッカーで魅了する伝統クラブ。',
    stadiumGourmet: 'シウマイ、サンマーメン', sightseeing: 'みなとみらい、横浜中華街', mascot: 'マリノス君' },
  { id: 'fctokyo',    name: 'FC東京',                    division: 'J1', region: '関東',   prefecture: '東京都', color: '#102E81',
    vector: { shoubu:  0, keiei: +1, kansen: +1, kanshin:  0 },
    description: '首都・東京を背負うシティクラブ。バランス感覚に優れたサッカーと洗練されたスタジアム体験。',
    stadiumGourmet: '青赤横丁、東京どら焼き', sightseeing: '深大寺、調布', mascot: '東京ドロンパ' },
  { id: 'verdy',      name: '東京ヴェルディ',            division: 'J1', region: '関東',   prefecture: '東京都', color: '#00714A',
    vector: { shoubu: -1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '読売クラブから続く名門。テクニックと美学を重んじる、Jリーグの始祖のひとつ。',
    stadiumGourmet: '緑のスタグル、味スタグルメ', sightseeing: '府中・国立、調布', mascot: 'ヴェルディ君' },
  { id: 'reysol',     name: '柏レイソル',                division: 'J1', region: '関東',   prefecture: '千葉県', color: '#FCB116',
    vector: { shoubu: +1, keiei: -1, kansen: +1, kanshin:  0 },
    description: 'アカデミーから個性派を量産する黄色いタレント工房。アグレッシブなサッカーが持ち味。',
    stadiumGourmet: '柏スタグル、レイソルカレー', sightseeing: '手賀沼、柏の葉', mascot: 'レイくん・ソルくん' },
  { id: 'grampus',    name: '名古屋グランパス',          division: 'J1', region: '東海',   prefecture: '愛知県', color: '#E60012',
    vector: { shoubu: +1, keiei: +1, kansen:  0, kanshin:  0 },
    description: '中部地方の盟主。堅実な守備をベースにタイトルを狙う、安定志向の伝統クラブ。',
    stadiumGourmet: '味噌カツ、手羽先', sightseeing: '名古屋城、熱田神宮', mascot: 'グランパスくんファミリー' },
  { id: 'gamba',      name: 'ガンバ大阪',                division: 'J1', region: '関西',   prefecture: '大阪府', color: '#0B2A75',
    vector: { shoubu:  0, keiei:  0, kansen: +2, kanshin:  0 },
    description: 'テクニックと攻撃力で時代を築いた青と黒。北摂の熱量と派手なサッカーを両立してきた名門。',
    stadiumGourmet: 'たこ焼き、お好み焼き', sightseeing: '万博記念公園、太陽の塔', mascot: 'ガンバボーイ' },
  { id: 'cerezo',     name: 'セレッソ大阪',              division: 'J1', region: '関西',   prefecture: '大阪府', color: '#D8127D',
    vector: { shoubu:  0, keiei: -1, kansen: +1, kanshin:  0 },
    description: '桜色のアタッカー集団。育成型クラブとして数多くの日本代表を輩出してきた攻撃の名門。',
    stadiumGourmet: '桜スタグル、たこ焼き', sightseeing: '長居公園、なんば', mascot: 'ロビー' },
  { id: 'kobe',       name: 'ヴィッセル神戸',            division: 'J1', region: '関西',   prefecture: '兵庫県', color: '#9E1B32',
    vector: { shoubu: +2, keiei: +2, kansen:  0, kanshin:  0 },
    description: 'スター選手を集めた現代の盟主。資金力と個の力でタイトルを獲り続ける、関西の派手な巨人。',
    stadiumGourmet: '神戸牛、明石焼き', sightseeing: 'ハーバーランド、北野異人館', mascot: 'モーヴィ' },
  { id: 'sanfrecce',  name: 'サンフレッチェ広島',        division: 'J1', region: '中国',   prefecture: '広島県', color: '#5E0F75',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '規律と組織のお手本。育成も巧みで、堅守と精密な戦術で頂点に立った経験を持つ。',
    stadiumGourmet: '広島お好み焼き、汁なし担々麺', sightseeing: '原爆ドーム、宮島', mascot: 'サンチェ・フレッチェ' },
  { id: 'avispa',     name: 'アビスパ福岡',              division: 'J1', region: '九州',   prefecture: '福岡県', color: '#1C3F94',
    vector: { shoubu: +1, keiei:  0, kansen: +1, kanshin:  0 },
    description: '九州を代表する堅守のチーム。専守速攻のスタイルと、博多の熱量あるサポーターが魅力。',
    stadiumGourmet: 'もつ鍋、博多ラーメン', sightseeing: '中洲、太宰府天満宮', mascot: 'アビー・ビビーくん' },
  { id: 'kyoto',      name: '京都サンガF.C.',            division: 'J1', region: '関西',   prefecture: '京都府', color: '#582C83',
    vector: { shoubu: +1, keiei:  0, kansen: +1, kanshin:  0 },
    description: '走力とハイインテンシティを武器にする、紫のチャレンジャー。攻撃的サッカーで上を狙う。',
    stadiumGourmet: '京都グルメ、抹茶スイーツ', sightseeing: '金閣寺、伏見稲荷', mascot: 'パーサくん' },
  { id: 'machida',    name: 'FC町田ゼルビア',            division: 'J1', region: '関東',   prefecture: '東京都', color: '#003C71',
    vector: { shoubu: +2, keiei: +2, kansen: +1, kanshin:  0 },
    description: 'ハードワークと堅守速攻、徹底した勝利志向で急成長したクラブ。賛否を呼びつつ結果を出し続ける。',
    stadiumGourmet: '町田リス園グルメ、サクサクポテト', sightseeing: '町田リス園、薬師池公園', mascot: 'ゼルビー' },
  { id: 'chiba',      name: 'ジェフユナイテッド千葉',    division: 'J1', region: '関東',   prefecture: '千葉県', color: '#FFCC00',
    vector: { shoubu:  0, keiei:  0, kansen: +1, kanshin:  0 },
    description: '黄色と緑の伝統あるクラブ。オシム時代から続く走るサッカーの遺伝子を持つ。',
    stadiumGourmet: '千葉グルメ、なめろう', sightseeing: '幕張、千葉ポートタワー', mascot: 'ジェフィ・ユニティ' },
  { id: 'mito',       name: '水戸ホーリーホック',        division: 'J1', region: '関東',   prefecture: '茨城県', color: '#005CAB',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '育成型クラブの旗手。次々と才能を輩出し、地域と農業との連携でも知られる。',
    stadiumGourmet: '水戸納豆グルメ、ホーリーキッチン', sightseeing: '偕楽園、水戸城', mascot: 'ホーリーくん' },
  { id: 'shimizu',    name: '清水エスパルス',            division: 'J1', region: '東海',   prefecture: '静岡県', color: '#F39800',
    vector: { shoubu:  0, keiei:  0, kansen: +1, kanshin:  0 },
    description: 'サッカー王国・静岡の象徴。市民クラブとして長く愛されてきた橙色の名門。',
    stadiumGourmet: 'もつカレー、桜えびかき揚げ', sightseeing: '三保松原、清水港', mascot: 'パルちゃん' },
  { id: 'okayama',    name: 'ファジアーノ岡山',          division: 'J1', region: '中国',   prefecture: '岡山県', color: '#E60012',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '桃太郎旗のもと地域と歩んできたクラブ。安定した組織サッカーで上を狙う。',
    stadiumGourmet: 'デミカツ丼、ばら寿司', sightseeing: '後楽園、倉敷美観地区', mascot: 'ファジ丸' },
  { id: 'nagasaki',   name: 'V・ファーレン長崎',          division: 'J1', region: '九州',   prefecture: '長崎県', color: '#005CAB',
    vector: { shoubu: +1, keiei: +1, kansen:  0, kanshin:  0 },
    description: 'ジャパネット主導で躍進する九州クラブ。新スタジアム時代の到来とともに勢いを増す。',
    stadiumGourmet: 'ちゃんぽん、カステラ', sightseeing: 'ハウステンボス、グラバー園', mascot: 'ヴィヴィくん' },

  // ===== J2 =====
  { id: 'tosu',       name: 'サガン鳥栖',                division: 'J2', region: '九州',   prefecture: '佐賀県', color: '#E73828',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '限られた資金の中で育成と組織を磨き続ける、九州のしぶといクラブ。スタジアムの一体感も魅力。',
    stadiumGourmet: '佐賀牛、シシリアンライス', sightseeing: '吉野ヶ里、唐津', mascot: 'ウィントス' },
  { id: 'shonan',     name: '湘南ベルマーレ',            division: 'J2', region: '関東',   prefecture: '神奈川県', color: '#2BAAE2',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '湘南スタイル＝走り続ける90分。家族とゆるく楽しむファミリー層に愛され、地元と歩むクラブ。',
    stadiumGourmet: '湘南しらす、丼もの', sightseeing: '江ノ島、湘南海岸', mascot: 'キングベルくん' },
  { id: 'iwata',      name: 'ジュビロ磐田',              division: 'J2', region: '東海',   prefecture: '静岡県', color: '#0085C7',
    vector: { shoubu: +1, keiei: -1, kansen: +1, kanshin:  0 },
    description: '黄金期の名手たちが築いた伝統。組織的なパスサッカーの系譜を引き継ぐ、サッカー王国・静岡の雄。',
    stadiumGourmet: '袋井クラウンメロン、磐田餃子', sightseeing: '掛川城、舘山寺温泉', mascot: 'ジュビロくん' },
  { id: 'sapporo',    name: '北海道コンサドーレ札幌',    division: 'J2', region: '北海道', prefecture: '北海道', color: '#C7000C',
    vector: { shoubu: -1, keiei:  0, kansen:  0, kanshin:  0 },
    description: 'ミシャ式の攻撃サッカーで一時代を築いた赤と黒。リスクを取って撃ち合うスタイルが愛される。',
    stadiumGourmet: 'ジンギスカン、ザンギ', sightseeing: '札幌時計台、すすきの', mascot: 'ドーレくん' },
  { id: 'niigata',    name: 'アルビレックス新潟',        division: 'J2', region: '北信越', prefecture: '新潟県', color: '#F37A1F',
    vector: { shoubu: -1, keiei: -2, kansen: -2, kanshin:  0 },
    description: '全国屈指のサポーター動員を誇る地元密着クラブ。ビッグスワンに集う家族層と一緒に応援する空気が魅力。',
    stadiumGourmet: 'へぎそば、新潟米のおにぎり', sightseeing: '佐渡、苗場', mascot: 'アルビくん・スワンちゃん' },
  { id: 'yokohamafc', name: '横浜FC',                    division: 'J2', region: '関東',   prefecture: '神奈川県', color: '#0072CE',
    vector: { shoubu:  0, keiei:  0, kansen:  0, kanshin:  0 },
    description: 'フリューゲルス消滅から市民の手で生まれたクラブ。粘り強く昇格と残留を勝ち取り続ける。',
    stadiumGourmet: '三ツ沢グルメ', sightseeing: '横浜、三ツ沢公園', mascot: 'フリ丸' },
  { id: 'omiya',      name: '大宮アルディージャ',        division: 'J2', region: '関東',   prefecture: '埼玉県', color: '#FF6600',
    vector: { shoubu:  0, keiei: +1, kansen:  0, kanshin:  0 },
    description: 'オレンジの堅実派。エレベーターと呼ばれた粘り強さがアイデンティティ。',
    stadiumGourmet: '氷川だんご、大宮ナポリタン', sightseeing: '鉄道博物館、氷川神社', mascot: 'アルディ・ミーヤ' },
  { id: 'sendai',     name: 'ベガルタ仙台',              division: 'J2', region: '東北',   prefecture: '宮城県', color: '#FFCC00',
    vector: { shoubu:  0, keiei:  0, kansen: +1, kanshin:  0 },
    description: '東北の盟主を自負する金と紫。震災後、地域と一緒に再起した物語を持つ。',
    stadiumGourmet: '牛タン、笹かまぼこ', sightseeing: '松島、青葉城', mascot: 'ベガッ太' },
  { id: 'yamagata',   name: 'モンテディオ山形',          division: 'J2', region: '東北',   prefecture: '山形県', color: '#0066B3',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '山形の県民総参加型クラブ。地方創生のモデルケースとしても語られる存在。',
    stadiumGourmet: '芋煮、米沢牛', sightseeing: '蔵王、銀山温泉', mascot: 'ディーオ' },
  { id: 'akita',      name: 'ブラウブリッツ秋田',        division: 'J2', region: '東北',   prefecture: '秋田県', color: '#003E92',
    vector: { shoubu: +1, keiei: -1, kansen: +1, kanshin:  0 },
    description: '圧倒的なハードワークとパワー系の堅守速攻で旋風を巻き起こした「秋田スタイル」。',
    stadiumGourmet: 'きりたんぽ、稲庭うどん', sightseeing: 'なまはげ、田沢湖', mascot: 'ブラウゴン' },
  { id: 'kofu',       name: 'ヴァンフォーレ甲府',        division: 'J2', region: '甲信越', prefecture: '山梨県', color: '#1E3A8A',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '限られたリソースから天皇杯制覇まで成し遂げた、地域密着の戦士たち。',
    stadiumGourmet: 'ほうとう、もつ煮', sightseeing: '昇仙峡、富士五湖', mascot: 'ヴァンくん・フォーレちゃん' },
  { id: 'tokushima',  name: '徳島ヴォルティス',          division: 'J2', region: '四国',   prefecture: '徳島県', color: '#0099CC',
    vector: { shoubu:  0, keiei:  0, kansen: -1, kanshin:  0 },
    description: 'スペイン系のパスサッカーを志向し続ける四国の青。技術と組織を重んじる。',
    stadiumGourmet: '徳島ラーメン、鳴門わかめ', sightseeing: '阿波踊り、鳴門の渦潮', mascot: 'ヴォルタくん' },
  { id: 'oita',       name: '大分トリニータ',            division: 'J2', region: '九州',   prefecture: '大分県', color: '#005AAC',
    vector: { shoubu:  0, keiei:  0, kansen:  0, kanshin:  0 },
    description: 'ナビスコ杯制覇の経験を持つ青。ボール保持型のスタイルで強豪に挑む。',
    stadiumGourmet: 'とり天、関アジ', sightseeing: '別府温泉、湯布院', mascot: 'ニータン' },
  { id: 'fujieda',    name: '藤枝MYFC',                  division: 'J2', region: '東海',   prefecture: '静岡県', color: '#00ADC8',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: 'サッカー王国・静岡の若手育成型クラブ。テクニカルなパスサッカーで上位を目指す青いチャレンジャー。',
    stadiumGourmet: '藤枝サッカーK、玉露', sightseeing: '蓮花寺池公園、大井川', mascot: 'フジッピー' },
  { id: 'hachinohe',  name: 'ヴァンラーレ八戸',          division: 'J2', region: '東北',   prefecture: '青森県', color: '#0066B3',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '青森の海風と共に戦うクラブ。地域から積み上げる本物の地元密着型。',
    stadiumGourmet: 'せんべい汁、いちご煮', sightseeing: '蕪島、種差海岸', mascot: 'ヴァン太' },
  { id: 'iwaki',      name: 'いわきFC',                  division: 'J2', region: '東北',   prefecture: '福島県', color: '#D32027',
    vector: { shoubu: +2, keiei: +1, kansen:  0, kanshin:  0 },
    description: '「日本のフィジカルスタンダードを変える」を掲げて急成長。圧倒的な走力で殴り合う。',
    stadiumGourmet: 'メヒカリの唐揚げ、サンマ', sightseeing: 'アクアマリンふくしま、塩屋崎', mascot: 'ハーマー' },
  { id: 'toyama',     name: 'カターレ富山',              division: 'J2', region: '北信越', prefecture: '富山県', color: '#003F8E',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '立山と日本海に挟まれた青。地道なクラブ運営で長くJの舞台に立ち続ける。',
    stadiumGourmet: 'ます寿司、ホタルイカ', sightseeing: '立山黒部、五箇山', mascot: 'ライカくん' },
  { id: 'imabari',    name: 'FC今治',                    division: 'J2', region: '四国',   prefecture: '愛媛県', color: '#FF6600',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '岡田武史氏が率いる「岡田メソッド」のクラブ。理論的な育成と組織サッカーで注目を集める。',
    stadiumGourmet: '焼豚玉子飯、鯛めし', sightseeing: 'しまなみ海道、来島海峡', mascot: 'Q1グランパパ' },
  { id: 'tegevajaro', name: 'テゲバジャーロ宮崎',        division: 'J2', region: '九州',   prefecture: '宮崎県', color: '#005BAC',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '南九州の青。地域とともに地道に階段を上る挑戦者。',
    stadiumGourmet: 'チキン南蛮、宮崎牛', sightseeing: '高千穂峡、青島', mascot: 'テゲバンビ' },
  { id: 'tochigi-city', name: '栃木シティ',              division: 'J2', region: '関東',   prefecture: '栃木県', color: '#000080',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '栃木SCに続いて誕生した北関東の青。地域と新しい挑戦の歴史を紡ぐ。',
    stadiumGourmet: '宇都宮餃子、いちご', sightseeing: '蔵の街・栃木、日光', mascot: 'シティくん' },

  // ===== J3 (JLSP では現在対象外、参考として保持) =====
  { id: 'tochigi',    name: '栃木SC',                    division: 'J3', region: '関東',   prefecture: '栃木県', color: '#FFC72C',
    vector: { shoubu: +1, keiei: -1, kansen: +1, kanshin:  0 },
    description: '黄色と紺の闘魂集団。フィジカルで殴り合うハードワークが代名詞。',
    stadiumGourmet: '宇都宮餃子、レモン牛乳', sightseeing: '日光、宇都宮', mascot: 'トッキー' },
  { id: 'gunma',      name: 'ザスパ群馬',                division: 'J3', region: '関東',   prefecture: '群馬県', color: '#0093D6',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '温泉と上州の風土に支えられたクラブ。地域密着の粘り強さが持ち味。',
    stadiumGourmet: '焼きまんじゅう、上州牛', sightseeing: '草津温泉、伊香保', mascot: 'ザスパーク' },
  { id: 'matsumoto',  name: '松本山雅FC',                division: 'J3', region: '甲信越', prefecture: '長野県', color: '#2E7D32',
    vector: { shoubu:  0, keiei: -1, kansen: +2, kanshin:  0 },
    description: '信州山岳地帯のクラブ。緑のサポーターが作るアルウィンの一体感は日本屈指。',
    stadiumGourmet: '信州そば、おやき', sightseeing: '松本城、上高地', mascot: 'ガンズくん' },
  { id: 'yamaguchi',  name: 'レノファ山口FC',            division: 'J3', region: '中国',   prefecture: '山口県', color: '#F4761B',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: 'ボールを保持して攻め抜く美しいサッカーを志向。育成と挑戦の物語が魅力。',
    stadiumGourmet: '瓦そば、ふぐ', sightseeing: '錦帯橋、秋吉台', mascot: 'レノ丸' },
  { id: 'ehime',      name: '愛媛FC',                    division: 'J3', region: '四国',   prefecture: '愛媛県', color: '#F39800',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: 'オレンジの伊予柑カラー。地元密着でJの舞台に踏ん張り続ける戦士たち。',
    stadiumGourmet: '鯛めし、じゃこ天', sightseeing: '道後温泉、松山城', mascot: 'オーレくん' },
  { id: 'kumamoto',   name: 'ロアッソ熊本',              division: 'J3', region: '九州',   prefecture: '熊本県', color: '#E40010',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '限られた予算ながらパスサッカーで上位を脅かしてきた赤。育成と挑戦のモデル。',
    stadiumGourmet: '馬刺し、太平燕', sightseeing: '熊本城、阿蘇山', mascot: 'ロアッソくん' },
  { id: 'kanazawa',   name: 'ツエーゲン金沢',            division: 'J3', region: '北信越', prefecture: '石川県', color: '#000000',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '北陸の黒。質実剛健なハードワークと粘りで上を狙うチャレンジャー。',
    stadiumGourmet: '金沢カレー、ノドグロ', sightseeing: '兼六園、ひがし茶屋街', mascot: 'ツエーゲンくん' },
  { id: 'fukushima',  name: '福島ユナイテッドFC',        division: 'J3', region: '東北',   prefecture: '福島県', color: '#E60012',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '震災と歩んできた赤。農業との連携や地域復興の象徴としての顔も持つ。',
    stadiumGourmet: '喜多方ラーメン、福島の桃', sightseeing: '会津若松、磐梯山', mascot: '福島ユナイテ君' },
  { id: 'sagamihara', name: 'SC相模原',                  division: 'J3', region: '関東',   prefecture: '神奈川県', color: '#006633',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '緑のサポーターと共に歩む地域密着型クラブ。粘り強く昇格を目指す。',
    stadiumGourmet: '津久井うどん、相模原グルメ', sightseeing: '宮ヶ瀬湖、相模湖', mascot: 'ガミティ' },
  { id: 'nagano',     name: 'AC長野パルセイロ',          division: 'J3', region: '甲信越', prefecture: '長野県', color: '#F77F00',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '信州の北側を担うオレンジ。地域と密に向き合うコミュニティクラブ。',
    stadiumGourmet: 'おやき、信州サーモン', sightseeing: '善光寺、戸隠', mascot: 'ライオー' },
  { id: 'gifu',       name: 'FC岐阜',                    division: 'J3', region: '東海',   prefecture: '岐阜県', color: '#006633',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '緑の地域密着クラブ。サポーターと一緒に這い上がる物語が魅力。',
    stadiumGourmet: '鶏ちゃん、飛騨牛', sightseeing: '白川郷、高山', mascot: 'ギッフィー' },
  { id: 'nara',       name: '奈良クラブ',                division: 'J3', region: '関西',   prefecture: '奈良県', color: '#003F8E',
    vector: { shoubu: -1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '「徹頭徹尾、攻撃」を掲げる挑戦者。理想を貫くサッカーで注目を集める青。',
    stadiumGourmet: '柿の葉寿司、奈良漬', sightseeing: '東大寺、奈良公園', mascot: 'シカッチェ' },
  { id: 'tottori',    name: 'ガイナーレ鳥取',            division: 'J3', region: '中国',   prefecture: '鳥取県', color: '#F39800',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '砂丘の街のオレンジ。芝生事業など地域貢献にも力を入れる小さな名門。',
    stadiumGourmet: '鳥取和牛、松葉ガニ', sightseeing: '鳥取砂丘、大山', mascot: 'ガイナマン' },
  { id: 'sanuki',     name: 'カマタマーレ讃岐',          division: 'J3', region: '四国',   prefecture: '香川県', color: '#003F8E',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: 'うどん県を背負う青。地元と密に歩むクラブ運営が持ち味。',
    stadiumGourmet: '讃岐うどん、骨付鳥', sightseeing: '金刀比羅宮、小豆島', mascot: 'サヌッキー' },
  { id: 'kagoshima',  name: '鹿児島ユナイテッドFC',      division: 'J3', region: '九州',   prefecture: '鹿児島県', color: '#E60012',
    vector: { shoubu: +1, keiei: -1, kansen:  0, kanshin:  0 },
    description: '桜島を背負う赤と黒。九州南部の盟主として上位昇格を狙う。',
    stadiumGourmet: '黒豚しゃぶしゃぶ、白くま', sightseeing: '桜島、知覧', mascot: 'ユないくん' },
  { id: 'ryukyu',     name: 'FC琉球',                    division: 'J3', region: '沖縄',   prefecture: '沖縄県', color: '#E60012',
    vector: { shoubu:  0, keiei:  0, kansen: -1, kanshin:  0 },
    description: '沖縄唯一のJクラブ。南国の風と熱量、アジアへの玄関口としてのアイデンティティを持つ。',
    stadiumGourmet: 'ソーキそば、タコライス', sightseeing: '首里城、美ら海水族館', mascot: 'ジンベーニョ' },
  { id: 'kochi',      name: '高知ユナイテッドSC',        division: 'J3', region: '四国',   prefecture: '高知県', color: '#E60012',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '高知の希望を背負う赤。Jの舞台で土佐の誇りを示し続ける。',
    stadiumGourmet: '鰹のたたき、皿鉢料理', sightseeing: '桂浜、四万十川', mascot: 'ぼうしくん' },
  { id: 'ococuma',    name: 'FC大阪',                    division: 'J3', region: '関西',   prefecture: '大阪府', color: '#0E6FB2',
    vector: { shoubu: +1, keiei:  0, kansen: +1, kanshin:  0 },
    description: '大阪3つ目のクラブを目指す青。市民クラブとして地域に根ざす成長株。',
    stadiumGourmet: '串カツ、たこ焼き', sightseeing: '通天閣、大阪城', mascot: 'ガンガン' },
  { id: 'shiga',      name: 'レイラック滋賀FC',          division: 'J3', region: '関西',   prefecture: '滋賀県', color: '#0048AA',
    vector: { shoubu:  0, keiei: -1, kansen: -1, kanshin:  0 },
    description: '琵琶湖から生まれた青いクラブ。地域に根ざし、若手育成と挑戦の物語を紡ぐ関西の新興勢力。',
    stadiumGourmet: '近江牛、ふなずし', sightseeing: '琵琶湖、彦根城', mascot: 'レイ太' },
  { id: 'kitakyushu', name: 'ギラヴァンツ北九州',        division: 'J3', region: '九州',   prefecture: '福岡県', color: '#FFC900',
    vector: { shoubu:  0, keiei: -1, kansen:  0, kanshin:  0 },
    description: '北九州の黄色いクラブ。地元密着で粘り強く昇格を目指す、九州北部のチャレンジャー。',
    stadiumGourmet: '焼きうどん、もつ鍋', sightseeing: '小倉城、門司港レトロ', mascot: 'ギランダ・ヴァンダ' },
]

/**
 * RAW_CLUBS の vector を override マップで上書きしたものを返す (全60クラブ)。
 * SSR 経路では DB から取得した overrides を、ビルド時/テスト時は vectors.json をそれぞれ渡す。
 */
export function applyVectorOverrides(overrideMap) {
  return RAW_CLUBS.map((c) => {
    const o = overrideMap[c.id]
    if (!o) return c
    return { ...c, vector: { ...c.vector, ...o } }
  })
}

/** J1+J2 にフィルタ。診断対象はこの 40 クラブ。 */
export function filterDiagnoseScope(clubs) {
  return clubs.filter((c) => CLUB_DIVISIONS.includes(c.division))
}

/** ビルド時 (vectors.json) を適用した全60クラブ。 */
export const ALL_CLUBS = applyVectorOverrides(vectorOverrides)

/** ビルド時の JLSP 対象 40クラブ (J1+J2)。DB を見ない静的経路の既定。*/
export const CLUBS = filterDiagnoseScope(ALL_CLUBS)

/** RAW_CLUBS が持つ素の vector (overrides 適用前) を id をキーに引けるマップ。*/
export const BASE_VECTORS = Object.fromEntries(RAW_CLUBS.map((c) => [c.id, c.vector]))
